
NODENAMES_METRICS = [
    'boottime',
    'bytes_in',
    'bytes_out',
    'cpu_idle',
    'cpu_nice',
    'cpu_system',
    'cpu_user',
    'cpu_wio',
    'default.StartupProgress.ElapsedTime',
    'default.StartupProgress.LoadingEditsCount',
    'default.StartupProgress.LoadingEditsElapsedTime',
    'default.StartupProgress.LoadingEditsPercentComplete',
    'default.StartupProgress.LoadingEditsTotal',
    'default.StartupProgress.LoadingFsImageCount',
    'default.StartupProgress.LoadingFsImageElapsedTime',
    'default.StartupProgress.LoadingFsImagePercentComplete',
    'default.StartupProgress.LoadingFsImageTotal',
    'default.StartupProgress.PercentComplete',
    'default.StartupProgress.SafeModeCount',
    'default.StartupProgress.SafeModeElapsedTime',
    'default.StartupProgress.SafeModePercentComplete',
    'default.StartupProgress.SafeModeTotal',
    'default.StartupProgress.SavingCheckpointCount',
    'default.StartupProgress.SavingCheckpointElapsedTime',
    'default.StartupProgress.SavingCheckpointPercentComplete',
    'default.StartupProgress.SavingCheckpointTotal',
    'dfs.FSNamesystem.BlockCapacity',
    'dfs.FSNamesystem.BlocksTotal',
    'dfs.FSNamesystem.CapacityRemaining',
    'dfs.FSNamesystem.CapacityRemainingGB',
    'dfs.FSNamesystem.CapacityTotal',
    'dfs.FSNamesystem.CapacityTotalGB',
    'dfs.FSNamesystem.CapacityUsed',
    'dfs.FSNamesystem.CapacityUsedGB',
    'dfs.FSNamesystem.CapacityUsedNonDFS',
    'dfs.FSNamesystem.CorruptBlocks',
    'metricssystem.MetricsSystem.NumAllSinks',
    'metricssystem.MetricsSystem.NumAllSources',
    'metricssystem.MetricsSystem.PublishAvgTime',
    'metricssystem.MetricsSystem.PublishNumOps',
    'metricssystem.MetricsSystem.Sink_timelineAvgTime',
    'metricssystem.MetricsSystem.Sink_timelineDropped',
    'metricssystem.MetricsSystem.Sink_timelineNumOps',
    'metricssystem.MetricsSystem.Sink_timelineQsize',
    'metricssystem.MetricsSystem.SnapshotAvgTime',
    'metricssystem.MetricsSystem.SnapshotNumOps',
    'part_max_used',
    'pkts_in',
    'pkts_out',
    'rpcdetailed.rpcdetailed.datanode.AddBlockNumOps',
    'rpcdetailed.rpcdetailed.datanode.BlockReceivedAndDeletedAvgTime',
    'rpcdetailed.rpcdetailed.datanode.BlockReceivedAndDeletedNumOps',
    'rpcdetailed.rpcdetailed.datanode.BlockReportAvgTime',
    'rpcdetailed.rpcdetailed.datanode.BlockReportNumOps',
    'rpcdetailed.rpcdetailed.datanode.CompleteAvgTime',
    'rpcdetailed.rpcdetailed.datanode.CompleteNumOps',
    'rpcdetailed.rpcdetailed.datanode.CreateAvgTime',
    'rpcdetailed.rpcdetailed.datanode.CreateNumOps',
    'rpcdetailed.rpcdetailed.datanode.DeleteAvgTime',
    'rpcdetailed.rpcdetailed.datanode.DeleteNumOps',
    'rpcdetailed.rpcdetailed.datanode.FsyncAvgTime',
    'rpcdetailed.rpcdetailed.datanode.FsyncNumOps',
    'rpcdetailed.rpcdetailed.datanode.GetBlockLocationsAvgTime',
    'rpcdetailed.rpcdetailed.datanode.GetBlockLocationsNumOps',
    'rpcdetailed.rpcdetailed.datanode.GetEditLogManifestAvgTime',
    'rpcdetailed.rpcdetailed.datanode.GetEditLogManifestNumOps',
    'rpcdetailed.rpcdetailed.datanode.GetFileInfoAvgTime',
    'rpcdetailed.rpcdetailed.datanode.GetFileInfoNumOps',
    'rpcdetailed.rpcdetailed.datanode.GetListingAvgTime',
    'rpcdetailed.rpcdetailed.datanode.GetListingNumOps',
    'rpcdetailed.rpcdetailed.datanode.GetServerDefaultsAvgTime',
    'rpcdetailed.rpcdetailed.datanode.GetServerDefaultsNumOps',
    'rpcdetailed.rpcdetailed.datanode.GetTransactionIdAvgTime',
    'rpcdetailed.rpcdetailed.datanode.GetTransactionIdNumOps',
    'rpcdetailed.rpcdetailed.datanode.IOExceptionAvgTime',
    'rpcdetailed.rpcdetailed.datanode.IOExceptionNumOps',
    'rpcdetailed.rpcdetailed.datanode.MkdirsAvgTime',
    'rpcdetailed.rpcdetailed.datanode.MkdirsNumOps',
    'rpcdetailed.rpcdetailed.datanode.PathIsNotEmptyDirectoryExceptionAvgTime',
    'rpcdetailed.rpcdetailed.datanode.PathIsNotEmptyDirectoryExceptionNumOps',
    'rpcdetailed.rpcdetailed.datanode.RecoverLeaseAvgTime',
    'rpcdetailed.rpcdetailed.datanode.RecoverLeaseNumOps',
    'rpcdetailed.rpcdetailed.datanode.RegisterDatanodeAvgTime',
    'rpcdetailed.rpcdetailed.datanode.RegisterDatanodeNumOps',
    'rpcdetailed.rpcdetailed.datanode.Rename2AvgTime',
    'rpcdetailed.rpcdetailed.datanode.Rename2NumOps',
    'rpcdetailed.rpcdetailed.datanode.RenameAvgTime',
    'rpcdetailed.rpcdetailed.datanode.RenameNumOps',
    'rpcdetailed.rpcdetailed.datanode.RenewLeaseAvgTime',
    'rpcdetailed.rpcdetailed.datanode.RenewLeaseNumOps',
    'rpcdetailed.rpcdetailed.datanode.RollEditLogAvgTime',
    'rpcdetailed.rpcdetailed.datanode.RollEditLogNumOps',
    'rpcdetailed.rpcdetailed.datanode.SendHeartbeatAvgTime',
    'rpcdetailed.rpcdetailed.datanode.SendHeartbeatNumOps',
    'rpcdetailed.rpcdetailed.datanode.SetOwnerAvgTime',
    'rpcdetailed.rpcdetailed.datanode.SetOwnerNumOps',
    'rpcdetailed.rpcdetailed.datanode.SetPermissionAvgTime',
    'rpcdetailed.rpcdetailed.datanode.SetPermissionNumOps',
    'rpcdetailed.rpcdetailed.datanode.SetReplicationAvgTime',
    'rpcdetailed.rpcdetailed.datanode.SetReplicationNumOps',
    'rpcdetailed.rpcdetailed.datanode.SetSafeModeAvgTime',
    'rpcdetailed.rpcdetailed.datanode.SetSafeModeNumOps',
    'rpcdetailed.rpcdetailed.datanode.SetTimesAvgTime',
    'rpcdetailed.rpcdetailed.datanode.SetTimesNumOps',
    'rpcdetailed.rpcdetailed.datanode.VersionRequestAvgTime',
    'rpcdetailed.rpcdetailed.datanode.VersionRequestNumOps',
    'rpcdetailed.rpcdetailed.healthcheck.AddBlockAvgTime',
    'rpcdetailed.rpcdetailed.healthcheck.AddBlockNumOps',
]


# https://mail-archives.apache.org/mod_mbox/ambari-commits/201502.mbox/%3Cf74df71ca2df4ca8ac8ca7665c74a903@git.apache.org%3E
# https://github.com/prajwalrao/ambari-metrics-grafana/blob/master/dashboards/grafana-yarn-applications.json
# https://community.cloudera.com/t5/Support-Questions/ambari-server-Hang-up/td-p/175503
# https://github.com/swagle/sidmisc/blob/master/scripts/Readme.md
YARN_ACTIVE_RES_MANAGERS = {
    'metricssystem.MetricsSystem.DroppedPubAll',
    'metricssystem.MetricsSystem.NumActiveSinks',
    'metricssystem.MetricsSystem.NumActiveSources',
    'metricssystem.MetricsSystem.NumAllSinks',
    'metricssystem.MetricsSystem.NumAllSources',
    'metricssystem.MetricsSystem.PublishAvgTime',
    'metricssystem.MetricsSystem.PublishNumOps',
    'metricssystem.MetricsSystem.Sink_timelineAvgTime',
    'metricssystem.MetricsSystem.Sink_timelineDropped',
    'metricssystem.MetricsSystem.Sink_timelineNumOps',
    'metricssystem.MetricsSystem.Sink_timelineQsize',
    'metricssystem.MetricsSystem.SnapshotAvgTime',
    'metricssystem.MetricsSystem.SnapshotNumOps',

    'pkts_in': 'metrics/network/pkts_in',
    'pkts_out': 'metrics/network/pkts_out',
    'proc_run': 'metrics/process/proc_run',
    'proc_total': 'metrics/process/proc_total',
    'rpc.rpc.CallQueueLength',

    # ???
    'yarn.ClusterMetrics.AMLaunchDelayAvgTime': 'yarn.ClusterMetrics.AMLaunchDelayAvgTime',
    'yarn.ClusterMetrics.AMLaunchDelayNumOps': 'yarn.ClusterMetrics.AMLaunchDelayNumOps',
    'yarn.ClusterMetrics.AMRegisterDelayAvgTime': 'yarn.ClusterMetrics.AMRegisterDelayAvgTime',
    'yarn.ClusterMetrics.AMRegisterDelayNumOps': 'yarn.ClusterMetrics.AMRegisterDelayNumOps',


    'yarn.ClusterMetrics.NumActiveNMs': 'metrics/yarn/ClusterMetrics/NumActiveNMs',
    'yarn.ClusterMetrics.NumDecommissionedNMs': 'metrics/yarn/ClusterMetrics/NumDecommissionedNMs',
    'yarn.ClusterMetrics.NumLostNMs': 'metrics/yarn/ClusterMetrics/NumLostNMs',
    'yarn.ClusterMetrics.NumRebootedNMs': 'metrics/yarn/ClusterMetrics/NumRebootedNMs',
    'yarn.ClusterMetrics.NumUnhealthyNMs': 'metrics/yarn/ClusterMetrics/NumUnhealthyNMs',
    'yarn.QueueMetrics.Queue=root.AMResourceLimitMB',
    'yarn.QueueMetrics.Queue=root.AMResourceLimitVCores',
    'yarn.QueueMetrics.Queue=root.ActiveApplications',
    'yarn.QueueMetrics.Queue=root.ActiveUsers',
    'yarn.QueueMetrics.Queue=root.AggregateContainersAllocated',
    'yarn.QueueMetrics.Queue=root.AggregateContainersReleased',
    'yarn.QueueMetrics.Queue=root.AllocatedContainers',
    'yarn.QueueMetrics.Queue=root.AllocatedMB',
    'yarn.QueueMetrics.Queue=root.AllocatedVCores',
    'yarn.QueueMetrics.Queue=root.AppAttemptFirstContainerAllocationDelayAvgTime',
    'yarn.QueueMetrics.Queue=root.AppAttemptFirstContainerAllocationDelayNumOps',
    'yarn.QueueMetrics.Queue=root.AppsCompleted',
    'yarn.QueueMetrics.Queue=root.AppsFailed',
    'yarn.QueueMetrics.Queue=root.AppsKilled',
    'yarn.QueueMetrics.Queue=root.AppsPending',
    'yarn.QueueMetrics.Queue=root.AppsRunning',
    'yarn.QueueMetrics.Queue=root.AppsSubmitted',
    'yarn.QueueMetrics.Queue=root.AvailableMB',
    'yarn.QueueMetrics.Queue=root.AvailableVCores',
    'yarn.QueueMetrics.Queue=root.PendingContainers',
    'yarn.QueueMetrics.Queue=root.PendingMB',
    'yarn.QueueMetrics.Queue=root.PendingVCores',
    'yarn.QueueMetrics.Queue=root.ReservedContainers',
    'yarn.QueueMetrics.Queue=root.ReservedMB',
    'yarn.QueueMetrics.Queue=root.ReservedVCores',
    'yarn.QueueMetrics.Queue=root.UsedAMResourceMB',
    'yarn.QueueMetrics.Queue=root.UsedAMResourceVCores',
    'yarn.QueueMetrics.Queue=root.default.AMResourceLimitMB',
    'yarn.QueueMetrics.Queue=root.default.AMResourceLimitVCores',
    'yarn.QueueMetrics.Queue=root.default.ActiveApplications',
    'yarn.QueueMetrics.Queue=root.default.ActiveUsers',
    'yarn.QueueMetrics.Queue=root.default.AggregateContainersAllocated',
    'yarn.QueueMetrics.Queue=root.default.AggregateContainersReleased',
    'yarn.QueueMetrics.Queue=root.default.AllocatedContainers',
    'yarn.QueueMetrics.Queue=root.default.AllocatedMB',
    'yarn.QueueMetrics.Queue=root.default.AllocatedVCores',
    'yarn.QueueMetrics.Queue=root.default.AppAttemptFirstContainerAllocationDelayAvgTime',
    'yarn.QueueMetrics.Queue=root.default.AppAttemptFirstContainerAllocationDelayNumOps',
    'yarn.QueueMetrics.Queue=root.default.AppsCompleted',
    'yarn.QueueMetrics.Queue=root.default.AppsFailed',
    'yarn.QueueMetrics.Queue=root.default.AppsKilled',
    'yarn.QueueMetrics.Queue=root.default.AppsPending',
    'yarn.QueueMetrics.Queue=root.default.AppsRunning',
    'yarn.QueueMetrics.Queue=root.default.AppsSubmitted',
    'yarn.QueueMetrics.Queue=root.default.AvailableMB',
    'yarn.QueueMetrics.Queue=root.default.AvailableVCores',
    'yarn.QueueMetrics.Queue=root.default.PendingContainers',
    'yarn.QueueMetrics.Queue=root.default.PendingMB',
    'yarn.QueueMetrics.Queue=root.default.PendingVCores',
    'yarn.QueueMetrics.Queue=root.default.ReservedContainers',
    'yarn.QueueMetrics.Queue=root.default.ReservedMB',
    'yarn.QueueMetrics.Queue=root.default.ReservedVCores',
    'yarn.QueueMetrics.Queue=root.default.UsedAMResourceMB',
    'yarn.QueueMetrics.Queue=root.default.UsedAMResourceVCores',
    'yarn.QueueMetrics.Queue=root.default.running_0',
    'yarn.QueueMetrics.Queue=root.default.running_1440',
    'yarn.QueueMetrics.Queue=root.default.running_300',
    'yarn.QueueMetrics.Queue=root.default.running_60',
    'yarn.QueueMetrics.Queue=root.running_0',
    'yarn.QueueMetrics.Queue=root.running_1440',
    'yarn.QueueMetrics.Queue=root.running_300',
    'yarn.QueueMetrics.Queue=root.running_60',
    'yarn.QueueMetrics.Queue=root.thriftsvr.AMResourceLimitMB',
    'yarn.QueueMetrics.Queue=root.thriftsvr.AMResourceLimitVCores',
    'yarn.QueueMetrics.Queue=root.thriftsvr.ActiveApplications',
    'yarn.QueueMetrics.Queue=root.thriftsvr.ActiveUsers',
    'yarn.QueueMetrics.Queue=root.thriftsvr.AggregateContainersAllocated',
    'yarn.QueueMetrics.Queue=root.thriftsvr.AggregateContainersReleased',
    'yarn.QueueMetrics.Queue=root.thriftsvr.AllocatedContainers',
    'yarn.QueueMetrics.Queue=root.thriftsvr.AllocatedMB',
    'yarn.QueueMetrics.Queue=root.thriftsvr.AllocatedVCores',
    'yarn.QueueMetrics.Queue=root.thriftsvr.AppAttemptFirstContainerAllocationDelayAvgTime',
    'yarn.QueueMetrics.Queue=root.thriftsvr.AppAttemptFirstContainerAllocationDelayNumOps',
    'yarn.QueueMetrics.Queue=root.thriftsvr.AppsCompleted',
    'yarn.QueueMetrics.Queue=root.thriftsvr.AppsFailed',
    'yarn.QueueMetrics.Queue=root.thriftsvr.AppsKilled',
    'yarn.QueueMetrics.Queue=root.thriftsvr.AppsPending',
    'yarn.QueueMetrics.Queue=root.thriftsvr.AppsRunning',
    'yarn.QueueMetrics.Queue=root.thriftsvr.AppsSubmitted',
    'yarn.QueueMetrics.Queue=root.thriftsvr.AvailableMB',
    'yarn.QueueMetrics.Queue=root.thriftsvr.AvailableVCores',
    'yarn.QueueMetrics.Queue=root.thriftsvr.PendingContainers',
    'yarn.QueueMetrics.Queue=root.thriftsvr.PendingMB',
    'yarn.QueueMetrics.Queue=root.thriftsvr.PendingVCores',
    'yarn.QueueMetrics.Queue=root.thriftsvr.ReservedContainers',
    'yarn.QueueMetrics.Queue=root.thriftsvr.ReservedMB',
    'yarn.QueueMetrics.Queue=root.thriftsvr.ReservedVCores',
    'yarn.QueueMetrics.Queue=root.thriftsvr.UsedAMResourceMB',
    'yarn.QueueMetrics.Queue=root.thriftsvr.UsedAMResourceVCores',
    'yarn.QueueMetrics.Queue=root.thriftsvr.running_0',
    'yarn.QueueMetrics.Queue=root.thriftsvr.running_1440',
    'yarn.QueueMetrics.Queue=root.thriftsvr.running_300',
    'yarn.QueueMetrics.Queue=root.thriftsvr.running_60',
}

# 'HDFS/component/DATANODE'
# https://www.mail-archive.com/commits@ambari.apache.org/msg31983.html
# http://mail-archives.apache.org/mod_mbox/ambari-commits/201506.mbox/%3Cfa7a4ae23d3749d1b7d90a5c83157931@git.apache.org%3E
YARN_ACTIVE_RES_MANAGERS = {
    'load_fifteen': 'metrics/load/load_fifteen',
    'load_five': 'metrics/load/load_five',
    'yarn.NodeManagerMetrics.AllocatedGB': 'metrics/yarn/AllocatedGB',
    'yarn.NodeManagerMetrics.AllocatedVCores': 'metrics/yarn/AllocatedVCores',
    'yarn.NodeManagerMetrics.AvailableGB': 'metrics/yarn/AvailableGB',
    'yarn.NodeManagerMetrics.AvailableVCores': 'metrics/yarn/AvailableVCores',
    'yarn.NodeManagerMetrics.BadLocalDirs': 'metrics/yarn/BadLocalDirs',
    'yarn.NodeManagerMetrics.BadLogDirs': 'metrics/yarn/BadLogDirs',
    'yarn.NodeManagerMetrics.ContainerLaunchDurationAvgTime': 'metrics/yarn/ContainerLaunchDurationAvgTime',
    'yarn.NodeManagerMetrics.ContainerLaunchDurationNumOps': 'metrics/yarn/ContainerLaunchDurationNumOps',
    'yarn.NodeManagerMetrics.ContainersCompleted': 'metrics/yarn/ContainersCompleted',
    'yarn.NodeManagerMetrics.ContainersFailed': 'metrics/yarn/ContainersFailed',
    'yarn.NodeManagerMetrics.ContainersIniting': 'metrics/yarn/ContainersIniting',
    'yarn.NodeManagerMetrics.ContainersKilled': 'metrics/yarn/ContainersKilled',
    'yarn.NodeManagerMetrics.ContainersLaunched': 'metrics/yarn/ContainersLaunched',
    'yarn.NodeManagerMetrics.ContainersRunning': 'metrics/yarn/ContainersRunning',
    'yarn.NodeManagerMetrics.GoodLocalDirsDiskUtilizationPerc': 'metrics/yarn/GoodLocalDirsDiskUtilizationPerc',
    'yarn.NodeManagerMetrics.GoodLogDirsDiskUtilizationPerc': 'metrics/yarn/GoodLogDirsDiskUtilizationPerc',
}
