
class BaseMetric:
    def __init__(self, name, path):
        self.name = name
        self.path = path


METRICS = [
    {
        'module': 'services/HDFS/components/NAMENODE',
        'metrics': [
            BaseMetric('boottime', 'metrics/boottime'),
            BaseMetric('bytes_in', 'metrics/network/bytes_in'),
            BaseMetric('bytes_out', 'metrics/network/bytes_out'),
            BaseMetric('cpu_idle', 'metrics/cpu/cpu_idle'),
            BaseMetric('cpu_nice', 'metrics/cpu/cpu_nice'),
            BaseMetric('cpu_system', 'metrics/cpu/cpu_system'),
            BaseMetric('cpu_user', 'metrics/cpu/cpu_user'),
            BaseMetric('cpu_wio', 'metrics/cpu/cpu_wio'),
            BaseMetric('default.StartupProgress.ElapsedTime', 'metrics/default/StartupProgress/ElapsedTime'),
            BaseMetric('default.StartupProgress.LoadingEditsCount', 'metrics/default/StartupProgress/LoadingEditsCount'),
            BaseMetric('default.StartupProgress.LoadingEditsElapsedTime', 'metrics/default/StartupProgress/LoadingEditsElapsedTime'),
            BaseMetric('default.StartupProgress.LoadingEditsPercentComplete', 'metrics/default/StartupProgress/LoadingEditsPercentComplete'),
            BaseMetric('default.StartupProgress.LoadingEditsTotal', 'metrics/default/StartupProgress/LoadingEditsTotal'),
            BaseMetric('default.StartupProgress.LoadingFsImageCount', 'metrics/default/StartupProgress/LoadingFsImageCount'),
            BaseMetric('default.StartupProgress.LoadingFsImageElapsedTime', 'metrics/default/StartupProgress/LoadingFsImageElapsedTime'),
            BaseMetric('default.StartupProgress.LoadingFsImagePercentComplete', 'metrics/default/StartupProgress/LoadingFsImagePercentComplete'),
            BaseMetric('default.StartupProgress.LoadingFsImageTotal', 'metrics/default/StartupProgress/LoadingFsImageTotal'),
            BaseMetric('default.StartupProgress.PercentComplete', 'metrics/default/StartupProgress/PercentComplete'),
            BaseMetric('default.StartupProgress.SafeModeCount', 'metrics/default/StartupProgress/SafeModeCount'),
            BaseMetric('default.StartupProgress.SafeModeElapsedTime', 'metrics/default/StartupProgress/SafeModeElapsedTime'),
            BaseMetric('default.StartupProgress.SafeModePercentComplete', 'metrics/default/StartupProgress/SafeModePercentComplete'),
            BaseMetric('default.StartupProgress.SafeModeTotal', 'metrics/default/StartupProgress/SafeModeTotal'),
            BaseMetric('default.StartupProgress.SavingCheckpointCount', 'metrics/default/StartupProgress/SavingCheckpointCount'),
            BaseMetric('default.StartupProgress.SavingCheckpointElapsedTime', 'metrics/default/StartupProgress/SavingCheckpointElapsedTime'),
            BaseMetric('default.StartupProgress.SavingCheckpointPercentComplete', 'metrics/default/StartupProgress/SavingCheckpointPercentComplete'),
            BaseMetric('default.StartupProgress.SavingCheckpointTotal', 'metrics/default/StartupProgress/SavingCheckpointTotal'),
            BaseMetric('dfs.FSNamesystem.BlockCapacity', 'metrics/dfs/FSNamesystem/BlockCapacity'),
            BaseMetric('dfs.FSNamesystem.BlocksTotal', 'metrics/dfs/FSNamesystem/BlocksTotal'),
            BaseMetric('dfs.FSNamesystem.CapacityRemaining', 'metrics/dfs/FSNamesystem/CapacityRemaining'),
            BaseMetric('dfs.FSNamesystem.CapacityRemainingGB', 'metrics/dfs/FSNamesystem/CapacityRemainingGB'),
            BaseMetric('dfs.FSNamesystem.CapacityTotal', 'metrics/dfs/FSNamesystem/CapacityTotal'),
            BaseMetric('dfs.FSNamesystem.CapacityTotalGB', 'metrics/dfs/FSNamesystem/CapacityTotalGB'),
            BaseMetric('dfs.FSNamesystem.CapacityUsed', 'metrics/dfs/FSNamesystem/CapacityUsed'),
            BaseMetric('dfs.FSNamesystem.CapacityUsedGB', 'metrics/dfs/FSNamesystem/CapacityUsedGB'),
            BaseMetric('dfs.FSNamesystem.CapacityUsedNonDFS', 'metrics/dfs/FSNamesystem/CapacityUsedNonDFS'),
            BaseMetric('dfs.FSNamesystem.CorruptBlocks', 'metrics/dfs/FSNamesystem/CorruptBlocks'),
            BaseMetric('metricssystem.MetricsSystem.NumAllSinks', 'metrics/metricssystem/MetricsSystem/NumAllSinks'),
            BaseMetric('metricssystem.MetricsSystem.NumAllSources', 'metrics/metricssystem/MetricsSystem/NumAllSources'),
            BaseMetric('metricssystem.MetricsSystem.PublishAvgTime', 'metrics/metricssystem/MetricsSystem/PublishAvgTime'),
            BaseMetric('metricssystem.MetricsSystem.PublishNumOps', 'metrics/metricssystem/MetricsSystem/PublishNumOps'),
            BaseMetric('metricssystem.MetricsSystem.Sink_timelineAvgTime', 'metrics/metricssystem/MetricsSystem/Sink_timelineAvgTime'),
            BaseMetric('metricssystem.MetricsSystem.Sink_timelineDropped', 'metrics/metricssystem/MetricsSystem/Sink_timelineDropped'),
            BaseMetric('metricssystem.MetricsSystem.Sink_timelineNumOps', 'metrics/metricssystem/MetricsSystem/Sink_timelineNumOps'),
            BaseMetric('metricssystem.MetricsSystem.Sink_timelineQsize', 'metrics/metricssystem/MetricsSystem/Sink_timelineQsize'),
            BaseMetric('metricssystem.MetricsSystem.SnapshotAvgTime', 'metrics/metricssystem/MetricsSystem/SnapshotAvgTime'),
            BaseMetric('metricssystem.MetricsSystem.SnapshotNumOps', 'metrics/metricssystem/MetricsSystem/SnapshotNumOps'),
            BaseMetric('part_max_used', 'metrics/disk/part_max_used'),
            BaseMetric('pkts_in', 'metrics/network/pkts_in'),
            BaseMetric('pkts_out', 'metrics/network/pkts_out'),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.AddBlockNumOps', 'metrics/rpcdetailed/datanode/complete_avg_time'),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.BlockReceivedAndDeletedAvgTime', 'metrics/rpcdetailed/datanode/block_received_and_deleted_avg_time'),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.BlockReceivedAndDeletedNumOps', 'metrics/rpcdetailed/datanode/block_received_and_deleted_num_ops'),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.BlockReportAvgTime', 'metrics/rpcdetailed/datanode/'),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.BlockReportNumOps', 'metrics/rpcdetailed/datanode/'),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.CompleteAvgTime', 'metrics/rpcdetailed/datanode/'),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.CompleteNumOps', 'metrics/rpcdetailed/datanode/'),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.CreateAvgTime', 'metrics/rpcdetailed/datanode/'),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.CreateNumOps', 'metrics/rpcdetailed/datanode/'),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.DeleteAvgTime', 'metrics/rpcdetailed/datanode/'),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.DeleteNumOps', 'metrics/rpcdetailed/datanode/'),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.FsyncAvgTime', 'metrics/rpcdetailed/datanode/'),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.FsyncNumOps', 'metrics/rpcdetailed/datanode/'),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.GetBlockLocationsAvgTime',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.GetBlockLocationsNumOps',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.GetEditLogManifestAvgTime',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.GetEditLogManifestNumOps',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.GetFileInfoAvgTime',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.GetFileInfoNumOps',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.GetListingAvgTime',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.GetListingNumOps',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.GetServerDefaultsAvgTime',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.GetServerDefaultsNumOps',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.GetTransactionIdAvgTime',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.GetTransactionIdNumOps',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.IOExceptionAvgTime',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.IOExceptionNumOps',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.MkdirsAvgTime',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.MkdirsNumOps',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.PathIsNotEmptyDirectoryExceptionAvgTime',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.PathIsNotEmptyDirectoryExceptionNumOps',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.RecoverLeaseAvgTime',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.RecoverLeaseNumOps',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.RegisterDatanodeAvgTime',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.RegisterDatanodeNumOps',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.Rename2AvgTime',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.Rename2NumOps',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.RenameAvgTime',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.RenameNumOps',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.RenewLeaseAvgTime',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.RenewLeaseNumOps',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.RollEditLogAvgTime',
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.RollEditLogNumOps',),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.SendHeartbeatAvgTime',),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.SendHeartbeatNumOps',),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.SetOwnerAvgTime',),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.SetOwnerNumOps',),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.SetPermissionAvgTime',),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.SetPermissionNumOps',),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.SetReplicationAvgTime',),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.SetReplicationNumOps',),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.SetSafeModeAvgTime',),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.SetSafeModeNumOps',),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.SetTimesAvgTime',),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.SetTimesNumOps',),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.VersionRequestAvgTime',),
            # BaseMetric('rpcdetailed.rpcdetailed.datanode.VersionRequestNumOps),
            # BaseMetric('rpcdetailed.rpcdetailed.healthcheck.AddBlockAvgTime',),
            # BaseMetric('rpcdetailed.rpcdetailed.healthcheck.AddBlockNumOps',),
        ]
    },


    # https://mail-archives.apache.org/mod_mbox/ambari-commits/201502.mbox/%3Cf74df71ca2df4ca8ac8ca7665c74a903@git.apache.org%3E
    # https://github.com/prajwalrao/ambari-metrics-grafana/blob/master/dashboards/grafana-yarn-applications.json
    # https://community.cloudera.com/t5/Support-Questions/ambari-server-Hang-up/td-p/175503
    # https://github.com/swagle/sidmisc/blob/master/scripts/Readme.md

    {
        'module': 'host_components',
        'params': {
            'HostRoles/component_name': 'RESOURCEMANAGER',
            'HostRoles/ha_state': 'ACTIVE'
        },
        'metrics': [
            BaseMetric('metricssystem.MetricsSystem.DroppedPubAll', 'metrics/metricssystem/MetricsSystem/DroppedPubAll'),
            BaseMetric('metricssystem.MetricsSystem.NumActiveSinks', 'metrics/metricssystem/MetricsSystem/NumActiveSinks'),
            BaseMetric('metricssystem.MetricsSystem.NumActiveSources', 'metrics/metricssystem/MetricsSystem/NumActiveSources'),
            BaseMetric('metricssystem.MetricsSystem.NumAllSinks', 'metrics/metricssystem/MetricsSystem/NumAllSinks'),
            BaseMetric('metricssystem.MetricsSystem.NumAllSources', 'metrics/metricssystem/MetricsSystem/NumAllSources'),
            BaseMetric('metricssystem.MetricsSystem.PublishAvgTime', 'metrics/metricssystem/MetricsSystem/PublishAvgTime'),
            BaseMetric('metricssystem.MetricsSystem.PublishNumOps', 'metrics/metricssystem/MetricsSystem/PublishNumOps'),
            BaseMetric('metricssystem.MetricsSystem.Sink_timelineAvgTime', 'metrics/metricssystem/MetricsSystem/Sink_timelineAvgTime'),
            BaseMetric('metricssystem.MetricsSystem.Sink_timelineDropped', 'metrics/metricssystem/MetricsSystem/Sink_timelineDropped'),
            BaseMetric('metricssystem.MetricsSystem.Sink_timelineNumOps', 'metrics/metricssystem/MetricsSystem/Sink_timelineNumOps'),
            BaseMetric('metricssystem.MetricsSystem.Sink_timelineQsize', 'metrics/metricssystem/MetricsSystem/Sink_timelineQsize'),
            BaseMetric('metricssystem.MetricsSystem.SnapshotAvgTime', 'metrics/metricssystem/MetricsSystem/SnapshotAvgTime'),
            BaseMetric('metricssystem.MetricsSystem.SnapshotNumOps', 'metrics/metricssystem/MetricsSystem/SnapshotNumOps'),
            BaseMetric('pkts_in', 'metrics/network/pkts_in'),
            BaseMetric('pkts_out', 'metrics/network/pkts_out'),
            BaseMetric('proc_run', 'metrics/process/proc_run'),
            BaseMetric('proc_total', 'metrics/process/proc_total'),
            BaseMetric('rpc.rpc.CallQueueLength', 'metrics/rpc/callQueueLen'),
            BaseMetric('yarn.ClusterMetrics.AMLaunchDelayAvgTime', 'metrics/yarn/ClusterMetrics/AMLaunchDelayAvgTime'),
            BaseMetric('yarn.ClusterMetrics.AMLaunchDelayNumOps', 'metrics/yarn/ClusterMetrics/AMLaunchDelayAvgTime'),
            BaseMetric('yarn.ClusterMetrics.AMRegisterDelayAvgTime', 'metrics/yarn/ClusterMetrics/AMLaunchDelayAvgTime'),
            BaseMetric('yarn.ClusterMetrics.AMRegisterDelayNumOps', 'metrics/yarn/ClusterMetrics/AMLaunchDelayAvgTime'),
            BaseMetric('yarn.ClusterMetrics.NumActiveNMs', 'metrics/yarn/ClusterMetrics/NumActiveNMs'),
            BaseMetric('yarn.ClusterMetrics.NumDecommissionedNMs', 'metrics/yarn/ClusterMetrics/NumDecommissionedNMs'),
            BaseMetric('yarn.ClusterMetrics.NumLostNMs', 'metrics/yarn/ClusterMetrics/NumLostNMs'),
            BaseMetric('yarn.ClusterMetrics.NumRebootedNMs', 'metrics/yarn/ClusterMetrics/NumRebootedNMs'),
            BaseMetric('yarn.ClusterMetrics.NumUnhealthyNMs', 'metrics/yarn/ClusterMetrics/NumUnhealthyNMs'),
            BaseMetric('yarn.QueueMetrics.Queue=root.AMResourceLimitMB', 'metrics/yarn/Queue/root/AMResourceLimitMB'),
            BaseMetric('yarn.QueueMetrics.Queue=root.AMResourceLimitVCores', 'metrics/yarn/Queue/root/AMResourceLimitVCores'),
            BaseMetric('yarn.QueueMetrics.Queue=root.ActiveApplications', 'metrics/yarn/Queue/root/ActiveApplications'),
            BaseMetric('yarn.QueueMetrics.Queue=root.ActiveUsers', 'metrics/yarn/Queue/root/ActiveUsers'),
            BaseMetric('yarn.QueueMetrics.Queue=root.AggregateContainersAllocated', 'metrics/yarn/Queue/root/AggregateContainersAllocated'),
            BaseMetric('yarn.QueueMetrics.Queue=root.AggregateContainersReleased', 'metrics/yarn/Queue/root/AggregateContainersReleased'),
            BaseMetric('yarn.QueueMetrics.Queue=root.AllocatedContainers', 'metrics/yarn/Queue/root/AllocatedContainers'),
            BaseMetric('yarn.QueueMetrics.Queue=root.AllocatedMB', 'metrics/yarn/Queue/root/AllocatedMB'),
            BaseMetric('yarn.QueueMetrics.Queue=root.AllocatedVCores', 'metrics/yarn/Queue/root/AllocatedVCores'),
            BaseMetric('yarn.QueueMetrics.Queue=root.AppAttemptFirstContainerAllocationDelayAvgTime', 'metrics/yarn/Queue/root/AppAttemptFirstContainerAllocationDelayAvgTime'),
            BaseMetric('yarn.QueueMetrics.Queue=root.AppAttemptFirstContainerAllocationDelayNumOps', 'metrics/yarn/Queue/root/AppAttemptFirstContainerAllocationDelayNumOps'),
            BaseMetric('yarn.QueueMetrics.Queue=root.AppsCompleted', 'metrics/yarn/Queue/root/AppsCompleted'),
            BaseMetric('yarn.QueueMetrics.Queue=root.AppsFailed', 'metrics/yarn/Queue/root/AppsFailed'),
            BaseMetric('yarn.QueueMetrics.Queue=root.AppsKilled', 'metrics/yarn/Queue/root/AppsKilled'),
            BaseMetric('yarn.QueueMetrics.Queue=root.AppsPending', 'metrics/yarn/Queue/root/AppsPending'),
            BaseMetric('yarn.QueueMetrics.Queue=root.AppsRunning', 'metrics/yarn/Queue/root/AppsRunning'),
            BaseMetric('yarn.QueueMetrics.Queue=root.AppsSubmitted', 'metrics/yarn/Queue/root/AppsSubmitted'),
            BaseMetric('yarn.QueueMetrics.Queue=root.AvailableMB', 'metrics/yarn/Queue/root/AvailableMB'),
            BaseMetric('yarn.QueueMetrics.Queue=root.AvailableVCores', 'metrics/yarn/Queue/root/AvailableVCores'),
            BaseMetric('yarn.QueueMetrics.Queue=root.PendingContainers', 'metrics/yarn/Queue/root/PendingContainers'),
            BaseMetric('yarn.QueueMetrics.Queue=root.PendingMB', 'metrics/yarn/Queue/root/PendingMB'),
            BaseMetric('yarn.QueueMetrics.Queue=root.PendingVCores', 'metrics/yarn/Queue/root/PendingVCores'),
            BaseMetric('yarn.QueueMetrics.Queue=root.ReservedContainers', 'metrics/yarn/Queue/root/ReservedContainers'),
            BaseMetric('yarn.QueueMetrics.Queue=root.ReservedMB', 'metrics/yarn/Queue/root/ReservedMB'),
            BaseMetric('yarn.QueueMetrics.Queue=root.ReservedVCores', 'metrics/yarn/Queue/root/ReservedVCores'),
            BaseMetric('yarn.QueueMetrics.Queue=root.UsedAMResourceMB', 'metrics/yarn/Queue/root/UsedAMResourceMB'),
            BaseMetric('yarn.QueueMetrics.Queue=root.UsedAMResourceVCores', 'metrics/yarn/Queue/root/UsedAMResourceVCores'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.AMResourceLimitMB', 'metrics/yarn/Queue/root/default/AMResourceLimitMB'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.AMResourceLimitVCores', 'metrics/yarn/Queue/root/default/AMResourceLimitVCores'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.ActiveApplications', 'metrics/yarn/Queue/root/default/ActiveApplications'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.ActiveUsers', 'metrics/yarn/Queue/root/default/ActiveUsers'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.AggregateContainersAllocated', 'metrics/yarn/Queue/root/default/AggregateContainersAllocated'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.AggregateContainersReleased', 'metrics/yarn/Queue/root/default/AggregateContainersReleased'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.AllocatedContainers', 'metrics/yarn/Queue/root/default/AllocatedContainers'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.AllocatedMB', 'metrics/yarn/Queue/root/default/AllocatedMB'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.AllocatedVCores', 'metrics/yarn/Queue/root/default/AllocatedVCores'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.AppAttemptFirstContainerAllocationDelayAvgTime', 'metrics/yarn/Queue/root/default/AppAttemptFirstContainerAllocationDelayAvgTime'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.AppAttemptFirstContainerAllocationDelayNumOps', 'metrics/yarn/Queue/root/default/AppAttemptFirstContainerAllocationDelayNumOps'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.AppsCompleted', 'metrics/yarn/Queue/root/default/AppsCompleted'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.AppsFailed', 'metrics/yarn/Queue/root/default/AppsFailed'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.AppsKilled', 'metrics/yarn/Queue/root/default/AppsKilled'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.AppsPending', 'metrics/yarn/Queue/root/default/AppsPending'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.AppsRunning', 'metrics/yarn/Queue/root/default/AppsRunning'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.AppsSubmitted', 'metrics/yarn/Queue/root/default/AppsSubmitted'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.AvailableMB', 'metrics/yarn/Queue/root/default/AvailableMB'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.AvailableVCores', 'metrics/yarn/Queue/root/default/AvailableVCores'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.PendingContainers', 'metrics/yarn/Queue/root/default/PendingContainers'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.PendingMB', 'metrics/yarn/Queue/root/default/PendingMB'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.PendingVCores', 'metrics/yarn/Queue/root/default/PendingVCores'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.ReservedContainers', 'metrics/yarn/Queue/root/default/ReservedContainers'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.ReservedMB', 'metrics/yarn/Queue/root/default/ReservedMB'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.ReservedVCores', 'metrics/yarn/Queue/root/default/ReservedVCores'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.UsedAMResourceMB', 'metrics/yarn/Queue/root/default/UsedAMResourceMB'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.UsedAMResourceVCores', 'metrics/yarn/Queue/root/default/UsedAMResourceVCores'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.running_0', 'metrics/yarn/Queue/root/default/running_0'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.running_1440', 'metrics/yarn/Queue/root/default/running_1440'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.running_300', 'metrics/yarn/Queue/root/default/running_300'),
            BaseMetric('yarn.QueueMetrics.Queue=root.default.running_60', 'metrics/yarn/Queue/root/default/running_60'),
            BaseMetric('yarn.QueueMetrics.Queue=root.running_0', 'metrics/yarn/Queue/root/running_0'),
            BaseMetric('yarn.QueueMetrics.Queue=root.running_1440', 'metrics/yarn/Queue/root/running_1440'),
            BaseMetric('yarn.QueueMetrics.Queue=root.running_300', 'metrics/yarn/Queue/root/running_300'),
            BaseMetric('yarn.QueueMetrics.Queue=root.running_60', 'metrics/yarn/Queue/root/running_60'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.AMResourceLimitMB', 'metrics/yarn/Queue/root/thriftsvr/AMResourceLimitMB'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.AMResourceLimitVCores', 'metrics/yarn/Queue/root/thriftsvr/AMResourceLimitVCores'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.ActiveApplications', 'metrics/yarn/Queue/root/thriftsvr/ActiveApplications'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.ActiveUsers', 'metrics/yarn/Queue/root/thriftsvr/ActiveUsers'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.AggregateContainersAllocated', 'metrics/yarn/Queue/root/thriftsvr/AggregateContainersAllocated'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.AggregateContainersReleased', 'metrics/yarn/Queue/root/thriftsvr/AggregateContainersReleased'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.AllocatedContainers', 'metrics/yarn/Queue/root/thriftsvr/AllocatedContainers'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.AllocatedMB', 'metrics/yarn/Queue/root/thriftsvr/AllocatedMB'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.AllocatedVCores', 'metrics/yarn/Queue/root/thriftsvr/AllocatedVCores'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.AppAttemptFirstContainerAllocationDelayAvgTime', 'metrics/yarn/Queue/root/thriftsvr/AppAttemptFirstContainerAllocationDelayAvgTime'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.AppAttemptFirstContainerAllocationDelayNumOps', 'metrics/yarn/Queue/root/thriftsvr/AppAttemptFirstContainerAllocationDelayNumOps'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.AppsCompleted', 'metrics/yarn/Queue/root/thriftsvr/AppsCompleted'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.AppsFailed', 'metrics/yarn/Queue/root/thriftsvr/AppsFailed'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.AppsKilled', 'metrics/yarn/Queue/root/thriftsvr/AppsKilled'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.AppsPending', 'metrics/yarn/Queue/root/thriftsvr/AppsPending'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.AppsRunning', 'metrics/yarn/Queue/root/thriftsvr/AppsRunning'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.AppsSubmitted', 'metrics/yarn/Queue/root/thriftsvr/AppsSubmitted'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.AvailableMB', 'metrics/yarn/Queue/root/thriftsvr/AvailableMB'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.AvailableVCores', 'metrics/yarn/Queue/root/thriftsvr/AvailableVCores'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.PendingContainers', 'metrics/yarn/Queue/root/thriftsvr/PendingContainers'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.PendingMB', 'metrics/yarn/Queue/root/thriftsvr/PendingMB'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.PendingVCores', 'metrics/yarn/Queue/root/thriftsvr/PendingVCores'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.ReservedContainers', 'metrics/yarn/Queue/root/thriftsvr/ReservedContainers'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.ReservedMB', 'metrics/yarn/Queue/root/thriftsvr/ReservedMB'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.ReservedVCores', 'metrics/yarn/Queue/root/thriftsvr/ReservedVCores'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.UsedAMResourceMB', 'metrics/yarn/Queue/root/thriftsvr/UsedAMResourceMB'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.UsedAMResourceVCores', 'metrics/yarn/Queue/root/thriftsvr/UsedAMResourceVCores'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.running_0', 'metrics/yarn/Queue/root/thriftsvr/running_0'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.running_1440', 'metrics/yarn/Queue/root/thriftsvr/running_1440'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.running_300', 'metrics/yarn/Queue/root/thriftsvr/running_300'),
            BaseMetric('yarn.QueueMetrics.Queue=root.thriftsvr.running_60', 'metrics/yarn/Queue/root/thriftsvr/running_60'),
        ]
    },

    {
        # https://www.mail-archive.com/commits@ambari.apache.org/msg31983.html
        # http://mail-archives.apache.org/mod_mbox/ambari-commits/201506.mbox/%3Cfa7a4ae23d3749d1b7d90a5c83157931@git.apache.org%3E
        'module': 'services/YARN/components/NODEMANAGER',
        'metrics': [
            BaseMetric('load_fifteen', 'metrics/load/load_fifteen'),
            BaseMetric('load_five', 'metrics/load/load_five'),
            BaseMetric('yarn.NodeManagerMetrics.AllocatedGB', 'metrics/yarn/AllocatedGB'),
            BaseMetric('yarn.NodeManagerMetrics.AllocatedVCores', 'metrics/yarn/AllocatedVCores'),
            BaseMetric('yarn.NodeManagerMetrics.AvailableGB', 'metrics/yarn/AvailableGB'),
            BaseMetric('yarn.NodeManagerMetrics.AvailableVCores', 'metrics/yarn/AvailableVCores'),
            BaseMetric('yarn.NodeManagerMetrics.BadLocalDirs', 'metrics/yarn/BadLocalDirs'),
            BaseMetric('yarn.NodeManagerMetrics.BadLogDirs', 'metrics/yarn/BadLogDirs'),
            BaseMetric('yarn.NodeManagerMetrics.ContainerLaunchDurationAvgTime', 'metrics/yarn/ContainerLaunchDurationAvgTime'),
            BaseMetric('yarn.NodeManagerMetrics.ContainerLaunchDurationNumOps', 'metrics/yarn/ContainerLaunchDurationNumOps'),
            BaseMetric('yarn.NodeManagerMetrics.ContainersCompleted', 'metrics/yarn/ContainersCompleted'),
            BaseMetric('yarn.NodeManagerMetrics.ContainersFailed', 'metrics/yarn/ContainersFailed'),
            BaseMetric('yarn.NodeManagerMetrics.ContainersIniting', 'metrics/yarn/ContainersIniting'),
            BaseMetric('yarn.NodeManagerMetrics.ContainersKilled', 'metrics/yarn/ContainersKilled'),
            BaseMetric('yarn.NodeManagerMetrics.ContainersLaunched', 'metrics/yarn/ContainersLaunched'),
            BaseMetric('yarn.NodeManagerMetrics.ContainersRunning', 'metrics/yarn/ContainersRunning'),
            BaseMetric('yarn.NodeManagerMetrics.GoodLocalDirsDiskUtilizationPerc', 'metrics/yarn/GoodLocalDirsDiskUtilizationPerc'),
            BaseMetric('yarn.NodeManagerMetrics.GoodLogDirsDiskUtilizationPerc', 'metrics/yarn/GoodLogDirsDiskUtilizationPerc'),
        ]
    }
]
